{
 "title": "OpenTelemetry Collector",
 "description": "Provides information about the status of the OpenTelemetry Collector",
 "tags": [ "opentelemetry" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "receiver", "label": "receiver", "query": "label_values(otelsvc_receiver)" },
   { "name": "exporter", "label": "exporter", "query": "label_values(otelsvc_exporter)" },
   { "name": "processor", "label": "processor", "query": "label_values(processor)" }
  ]
 },
 "panels": [
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Spans Received/Second",
   "type": "graph",
   "description": "Rate of spans successfully received per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_otelcol_receiver_received_spans{otelsvc_receiver=~\"$receiver\"}[1m])) by (otelsvc_receiver)",
     "legendFormat": "{{otelsvc_receiver}}"
    }
   ]
  },
  {
   "title": "Timeseries Received/Second",
   "type": "graph",
   "description": "Rate of timeseries successfully received per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_otelcol_receiver_received_timeseries{otelsvc_receiver=~\"$receiver\"}[1m])) by (otelsvc_receiver)",
     "legendFormat": "{{otelsvc_receiver}}"
    }
   ]
  },
  {
   "title": "Spans Dropped/Second",
   "type": "graph",
   "description": "Rate of spans dropped per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_otelcol_receiver_dropped_spans{otelsvc_receiver=~\"$receiver\"}[1m])) by (otelsvc_receiver)",
     "legendFormat": "{{otelsvc_receiver}}"
    }
   ]
  },
  {
   "title": "Timeseries Dropped/Second",
   "type": "graph",
   "description": "Rate of timeseries dropped per second.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_otelcol_receiver_dropped_timeseries{otelsvc_receiver=~\"$receiver\"}[1m])) by (otelsvc_receiver)",
     "legendFormat": "{{otelsvc_receiver}}"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Exported Spans/Second",
   "type": "graph",
   "description": "Rate of spans successfully exported per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_otelcol_exporter_received_spans{otelsvc_exporter=~\"$exporter\"}[1m])) by (otelsvc_exporter)",
     "legendFormat": "{{otelsvc_exporter}}"
    }
   ]
  },
  {
   "title": "Exported Timeseries/Second",
   "type": "graph",
   "description": "Rate of timeseries successfully exported per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_otelcol_exporter_received_timeseries{otelsvc_exporter=~\"$exporter\"}[1m])) by (otelsvc_exporter)",
     "legendFormat": "{{otelsvc_exporter}}"
    }
   ]
  },
  { "title": "Queued Retry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Queue Length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(oc_collector_queue_length{processor=~\"$processor\"}) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "In-queue Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oc_collector_queue_latency_sum{processor=~\"$processor\"} / oc_collector_queue_latency_count{processor=~\"$processor\"}) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Spans Enqueued/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_spans_received[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Batches Enqueued/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_batches_received[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Spans per Batch (avg from rates)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_spans_received{processor=~\"$processor\"}[1m]) / rate(oc_collector_batches_received{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Batches Successful Sent/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_success_send{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Spans Dropped/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_spans_dropped{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Batches Dropped/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_batches_dropped{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Successful Batches Sent Cumulative",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oc_collector_success_send{processor=~\"$processor\"}) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Enqueued Spans Cumulative",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oc_collector_spans_received{exporter=~\"$exporter\"}) by (exporter)",
     "legendFormat": "{{exporter}}"
    }
   ]
  },
  {
   "title": "Batches Failed to Send/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(oc_collector_fail_send{processor=~\"$processor\"}[1m])) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Batches Failed to Send Cumulative",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oc_collector_fail_send{processor=~\"$processor\"}) by (processor)",
     "legendFormat": "{{processor}}"
    }
   ]
  }
 ]
}