version: '3.3'
services:

  mysql:
    image: mysql:8.0.31
    container_name: ${CONTAINER_NAME_PREFIX}mysql
    restart: on-failure
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:${INNER_MYSQL_PORT}
    volumes:
      - ./mysql/init.d/nacos-db.sql:/docker-entrypoint-initdb.d/nacos-db.sql
    command:
      [
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --default-authentication-plugin=mysql_native_password
      ]

  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: ${CONTAINER_NAME_PREFIX}nacos-standalone-mysql
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8848/nacos/v1/console/health/readiness" ]
      interval: 10s
      timeout: 10s
      retries: 10
    env_file:
      - ./nacos/nacos-standalone-mysql.env
    ports:
      - ${NACOS_GRPC_PORT}:${NACOS_GRPC_PORT}
      - ${NACOS_SERVER_PORT}:${NACOS_SERVER_PORT}
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
        